apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-readenv
spec:
  selector:
    matchLabels:
      app: python-readenv
  replicas: 1
  template:
    metadata:
      labels:
        app: python-readenv 
    spec:
      containers:
      - name: python-readenv
        image: python-readenv
        imagePullPolicy: Never
        env:
          - name : SECRET
            valueFrom:
              secretKeyRef:
                name: python-readenv
                key: secret
          - name : ENV1
            valueFrom:
              secretKeyRef:
                name: python-readenv
                key: env1
          - name : ENV2
            valueFrom:
              secretKeyRef:
                name: python-readenv
                key: env2
      - name: secretsupdater
        image: secretsupdater
        imagePullPolicy: Never
        env:
          - name : VAULT_ADDR
            valueFrom:
              secretKeyRef:
                name: secrets-updater
                key: vault_addr
          - name : VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: secrets-updater
                key: vault_token
          - name : VAULT_SECRET_PATH
            valueFrom:
              secretKeyRef:
                name: secrets-updater
                key: vault_secret_path
          - name : VAULT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: secrets-updater
                key: vault_secret_key
          - name : APP_NAME
            valueFrom:
              secretKeyRef:
                name: secrets-updater
                key: app_name
          - name : NAMESPACE
            valueFrom:
              secretKeyRef:
                name: secrets-updater
                key: namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: python-readenv 
type: Opaque
data:
  secret: bXlzZWNyZXRwYXNzd29yZA==
  env1: dGVzdGUK
  env2: ***REMOVED***

---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-updater 
type: Opaque
data:
  vault_addr: aHR0cDovLzEwLjI0NC4xLjIK
  vault_token: cm9vdAo=
  vault_secret_path: cG9jCg==
  vault_secret_key: cGFzcwo=
  namespace: dmF1bHQK
  app_name: cHl0aG9uLXJlYWRlbnYK

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secrets-manager
rules:
- apiGroups: [""]
  resources: ["secrets", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secrets-manager
subjects:
- kind: ServiceAccount
  name: default
  namespace: vault
roleRef:
  kind: ClusterRole
  name: secrets-manager
  apiGroup: rbac.authorization.k8s.io
