from python:latest

WORKDIR app

COPY secretsupdate.py secretsupdate.py
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

ENV PYTHONUNBUFFERED=1

CMD ["python", "./secretsupdate.py"]
